name: Update Diagram Images on Rating Change

on:
  push:
    branches:
      - master
    paths:
      - 'rating.json'

jobs:
  update-diagrams:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install matplotlib

    - name: Run script
      run: python .github/workflows/scripts/visualizer.py
      working-directory: ${{ github.workspace }}

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update Diagram Images on Rating Change 